### ISSUE TITLE
"Log in with GitHub" stopped working

### ISSUE THREAD

**Issue by dtfinch** [JSJitsu/ai-battle-website#115]
https://jsfight.club/auth/github is giving the response:

    TypeError: dbHelper.getPlayer(...).then(...).done is not a function
        at /home/asuza/dev/jsjitsu/site/server/OAuthGithub.js:116:14
        at pass (/home/asuza/dev/jsjitsu/site/node_modules/passport/lib/authenticator.js:357:9)
        at Authenticator.deserializeUser (/home/asuza/dev/jsjitsu/site/node_modules/passport/lib/authenticator.js:362:5)
        at SessionStrategy.authenticate (/home/asuza/dev/jsjitsu/site/node_modules/passport/lib/strategies/session.js:60:10)
        at attempt (/home/asuza/dev/jsjitsu/site/node_modules/passport/lib/middleware/authenticate.js:361:16)
        at authenticate (/home/asuza/dev/jsjitsu/site/node_modules/passport/lib/middleware/authenticate.js:362:7)
        at Layer.handle [as handle_request] (/home/asuza/dev/jsjitsu/site/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/home/asuza/dev/jsjitsu/site/node_modules/express/lib/router/index.js:317:13)
        at /home/asuza/dev/jsjitsu/site/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/home/asuza/dev/jsjitsu/site/node_modules/express/lib/router/index.js:335:12)

**Comment by Asuza** [comment]
Thank you for the report! I will investigate as soon as I am able.

**Comment by Asuza** [comment]
@dtfinch please try again and let me know what you find.

**Comment by dtfinch** [comment]
It's working now.
