### ISSUE TITLE
Errors when running ./docker-startup.sh

### ISSUE THREAD

**Issue by Cyberf1** [JSJitsu/ai-battle-website#132]
After running ./docker-startup.sh I've got this output:
 * Starting PostgreSQL 9.5 database server                                                                                                                                                   [ OK ] 
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 632ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=1cc4b2 The platform linux is incompatible with this module, build skipped.
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 1s 114ms
public/app/account.tag -> public/build/all-tags.js
public/app/battle.tag -> public/build/all-tags.js
public/app/instructions.tag -> public/build/all-tags.js
public/app/leaderboard.tag -> public/build/all-tags.js
public/app/navigation.tag -> public/build/all-tags.js
public/app/parallax.tag -> public/build/all-tags.js
public/app/recent-battles.tag -> public/build/all-tags.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/app/node_modules/.bin/knex'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
-su: ./node_modules/connect-pg-simple/table.sql: No such file or directory
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'q'
Require stack:
- /app/gamerunner/game_logic/GameRunner.js
- /app/gamerunner/game_logic/LiveGameRunner.js
- /app/gamerunner/run-test-game.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/gamerunner/game_logic/GameRunner.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/gamerunner/game_logic/GameRunner.js',
    '/app/gamerunner/game_logic/LiveGameRunner.js',
    '/app/gamerunner/run-test-game.js'
  ]
}
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'better-console'
Require stack:
- /app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/server.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/server.js' ]
}

**Comment by Asuza** [comment]
This is likely my fault! I switched the repo to use Yarn PnP, but forgot to verify the changes in Docker. I will try to take a look when I have time.
