### ISSUE TITLE
Add scope to authentication to allow access to private repos

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#70]
This would allow users to hide their hero code behind a private repo, so other users can't simply copy their work. This should be opt-in, if possible, so users don't have to allow access to their private repos unless they want to.

**Comment by Asuza** [comment]
I believe this needs to be fixed on [this line](https://github.com/JSJitsu/ai-battle-website/blob/c63a22b837709eddab4d453294b45a31a0bc9175/server/OAuthGithub.js#L265) by adding a scope, as mentioned in the [documentation for passport-github2](https://www.npmjs.com/package/passport-github2). The [GitHub OAuth Documenation on Scopes](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/) describes the various scope settings in more detail.

**Comment by klemenzarn** [comment]
Hei, it's me form reddit thread. I manage to install vagrant and all dependencies, `but npm run` build gives me an error:

```
browserify ./node_modules/ai-battle-engine/index.js --standalone GameEngine > public/js/game-engine.js

[07:53:58] Using gulpfile ~/ai-battle-website/gulpfile.js
[07:53:58] Starting 'sass'...
[07:53:58] Finished 'sass' after 31 ms
[07:53:58] Starting 'build'...

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

GulpUglifyError: unable to minify JavaScript
    at createError (/home/vagrant/ai-battle-website/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/home/vagrant/ai-battle-website/node_modules/gulp-uglify/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/home/vagrant/ai-battle-website/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/home/vagrant/ai-battle-website/node_modules/gulp-uglify/minifier.js:79:19)
    at DestroyableTransform.Transform._read (/home/vagrant/ai-battle-website/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/vagrant/ai-battle-website/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/vagrant/ai-battle-website/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/vagrant/ai-battle-website/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/vagrant/ai-battle-website/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
```

**Comment by Asuza** [comment]
I'll try to reproduce this in the morning, but I wonder if the wrong version of Gulp or Uglify was installed when you ran `npm install`.

**Comment by klemenzarn** [comment]
Probably since npm install get the latest one because you are not saving extact version of dependency 

my `npm list --depth=0` is:

```
javascript-battle-website@1.0.0 /home/vagrant/ai-battle-website
├── ai-battle-engine@1.0.1 (git+https://github.com/JSJitsu/ai-battle-engine.git#552175ed131c3266494b3938a73ef960b0f0dd3b)
├── better-console@0.2.4
├── blanket@1.2.3
├── body-parser@1.18.2
├── browserfy@1.0.0 extraneous
├── browserify@13.3.0
├── chai@1.10.0
├── chai-spies@0.7.1
├── connect-pg-simple@3.1.2
├── eslint@3.19.0
├── eslint-config-airbnb@12.0.0
├── UNMET PEER DEPENDENCY eslint-plugin-import@2.8.0
├── eslint-plugin-jsx-a11y@2.2.3
├── eslint-plugin-react@6.10.3
├── express@4.16.2
├── express-session@1.15.6
├── gulp@3.9.1
├── gulp-clean-css@2.4.0
├── gulp-concat@2.6.1
├── gulp-rename@1.2.2
├── gulp-rev@7.1.2
├── gulp-sass@3.1.0
├── gulp-spa@0.2.2
├── gulp-uglify@2.1.2
├── minimist@1.2.0
├── mocha@1.21.5
├── morgan@1.9.0
├── passport@0.3.2
├── passport-github@1.1.0
├── passport-github2@0.1.11
├── pg@4.5.7
├── pg-db@1.1.0
├── q@1.5.1
└── request@2.79.0
```

**Comment by Asuza** [comment]
I updated _package.json_ to use specific versions and it seemed to work fine. Pull down the latest changes, possibly remove your _node_modules_ folder, and try it again. Let me know if anything goes awry.

**Comment by Asuza** [comment]
@klemenzarn, this feature has been added to the _riotjs_ branch, which is what is live on the site now.
